name: Generar Ejecutable Windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4 # Actualizado a v4

    - name: Configurar Python
      uses: actions/setup-python@v5 # Actualizado a v5
      with:
        python-version: '3.10'

    - name: Instalar librerias
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Crear EXE con PyInstaller
      run: pyinstaller --onefile --noconsole wedge_model.py

    - name: Subir el archivo final
      uses: actions/upload-artifact@v4 # ACTUALIZACIÓN CRÍTICA A v4
      with:
        name: Programa-Sintonia-Sismica
        path: dist/wedge_model.exe
